In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Admission_Predict.csv')

In [3]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.3 KB

In [5]:
df=df.drop(['Serial No.'],axis=1)

In [6]:
df.describe()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [7]:
scaler=StandardScaler()

In [8]:
X=df.drop(['Chance of Admit '],axis=1)
y=df['Chance of Admit ']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=42)

In [10]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

In [12]:
model=Sequential()

In [13]:
model.add(Dense(8,activation="relu",input_shape=(7,)))
model.add(Dense(4,activation="relu"))
model.add(Dense(1,activation="linear"))

In [14]:
model.compile(optimizer="adam",loss="mean_squared_error",metrics=["mse"])

In [15]:
model.fit(X_train,y_train,epochs=100,batch_size=20,verbose=1,validation_split=0.2)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.1548 - mse: 0.1548 - val_loss: 0.1526 - val_mse: 0.1526
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1091 - mse: 0.1091 - val_loss: 0.1320 - val_mse: 0.1320
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0907 - mse: 0.0907 - val_loss: 0.1201 - val_mse: 0.1201
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0782 - mse: 0.0782 - val_loss: 0.1029 - val_mse: 0.1029
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0680 - mse: 0.0680 - val_loss: 0.0914 - val_mse: 0.0914
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0593 - mse: 0.0593 - val_loss: 0.0810 - val_mse: 0.0810
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0527 - mse: 0.0527 - val_loss: 0.0747 - val_mse: 0.0747
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0469 - mse: 0.0469 - val_loss: 0.0685 - val_mse: 0.0685
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0422 - mse: 0.0422 - val_loss: 0.0632 - val_mse: 0.0632
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0388 - mse: 0.0388 - val_loss: 0.0582 - val_mse: 0.0582
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0358 - mse: 0.0358 - val_loss: 0.0543 - val_mse: 0.0543
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0334 - mse: 0.0334 - val_loss: 0.0507 - val_mse: 0.0507
Epoch 13/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0313 - mse: 0.0313 - val_loss: 0.0466 - val_mse: 0.0466
Epoch 14/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0293 - mse: 0.0293 - val_loss: 0.0440 - val_mse: 0.0440
Epoch 15/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0276 - mse: 0.0276 - val_loss: 0.0430 - val_mse: 0.0430
Epoch 16/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0262 - mse: 0.0262 - val_loss: 0.0405 - val_mse: 0.0405
Epoch 17/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0247 - mse: 0.0247 - val_loss: 0.0376 - val_mse: 0.0376
Epoch 18/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0238 - mse: 0.0238 - val_loss: 0.0352 - val_mse: 0.0352
Epoch 19/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0224 - mse: 0.0224 - val_loss: 0.0344 - val_mse: 0.0344
Epoch 20/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0216 - mse: 0.0216 - val_loss: 0.0334 - val_mse: 0.0334
Epoch 21/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0206 - mse: 0.0206 - val_loss: 0.0316 - val_mse: 0.0316
Epoch 22/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0197 - mse: 0.0197 - val_loss: 0.0304 - val_mse: 0.0304
Epoch 23/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0190 - mse: 0.0190 - val_loss: 0.0287 - val_mse: 0.0287
Epoch 24/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0182 - mse: 0.0182 - val_loss: 0.0278 - val_mse: 0.0278
Epoch 25/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0175 - mse: 0.0175 - val_loss: 0.0267 - val_mse: 0.0267
Epoch 26/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0169 - mse: 0.0169 - val_loss: 0.0255 - val_mse: 0.0255
Epoch 27/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0163 - mse: 0.0163 - val_loss: 0.0244 - val_mse: 0.0244
Epoch 28/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0157 - mse: 0.0157 - val_loss: 0.0234 - val_mse: 0.0234
Epoch 29/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0152 - mse: 0.0152 - val_loss: 0.0225 - val_mse: 0.0225
Epoch 30/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0147 - mse: 0.0147 - val_loss: 0.0220 - val_mse: 0.0220
Epoch 31/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0143 - mse: 0.0143 - val_loss: 0.0214 - val_mse: 0.0214
Epoch 32/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0138 - mse: 0.0138 - val_loss: 0.0202 - val_mse: 0.0202
Epoch 33/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0134 - mse: 0.0134 - val_loss: 0.0199 - val_mse: 0.0199
Epoch 34/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0130 - mse: 0.0130 - val_loss: 0.0192 - val_mse: 0.0192
Epoch 35/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0127 - mse: 0.0127 - val_loss: 0.0187 - val_mse: 0.0187
Epoch 36/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0124 - mse: 0.0124 - val_loss: 0.0181 - val_mse: 0.0181
Epoch 37/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0121 - mse: 0.0121 - val_loss: 0.0174 - val_mse: 0.0174
Epoch 38/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0118 - mse: 0.0118 - val_loss: 0.0172 - val_mse: 0.0172
Epoch 39/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0115 - mse: 0.0115 - val_loss: 0.0167 - val_mse: 0.0167
Epoch 40/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0113 - mse: 0.0113 - val_loss: 0.0163 - val_mse: 0.0163
Epoch 41/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0109 - mse: 0.0109 - val_loss: 0.0156 - val_mse: 0.0156
Epoch 42/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0106 - mse: 0.0106 - val_loss: 0.0155 - val_mse: 0.0155
Epoch 43/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mse: 0.0104 - val_loss: 0.0151 - val_mse: 0.0151
Epoch 44/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mse: 0.0103 - val_loss: 0.0151 - val_mse: 0.0151
Epoch 45/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0100 - mse: 0.0100 - val_loss: 0.0146 - val_mse: 0.0146
Epoch 46/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0099 - mse: 0.0099 - val_loss: 0.0141 - val_mse: 0.0141
Epoch 47/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0096 - mse: 0.0096 - val_loss: 0.0139 - val_mse: 0.0139
Epoch 48/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0095 - mse: 0.0095 - val_loss: 0.0138 - val_mse: 0.0138
Epoch 49/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0093 - mse: 0.0093 - val_loss: 0.0133 - val_mse: 0.0133
Epoch 50/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0091 - mse: 0.0091 - val_loss: 0.0131 - val_mse: 0.0131
Epoch 51/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0090 - mse: 0.0090 - val_loss: 0.0132 - val_mse: 0.0132
Epoch 52/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0089 - mse: 0.0089 - val_loss: 0.0129 - val_mse: 0.0129
Epoch 53/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0086 - mse: 0.0086 - val_loss: 0.0126 - val_mse: 0.0126
Epoch 54/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0085 - mse: 0.0085 - val_loss: 0.0124 - val_mse: 0.0124
Epoch 55/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0084 - mse: 0.0084 - val_loss: 0.0123 - val_mse: 0.0123
Epoch 56/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0082 - mse: 0.0082 - val_loss: 0.0122 - val_mse: 0.0122
Epoch 57/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0080 - mse: 0.0080 - val_loss: 0.0121 - val_mse: 0.0121
Epoch 58/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0080 - mse: 0.0080 - val_loss: 0.0118 - val_mse: 0.0118
Epoch 59/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0078 - mse: 0.0078 - val_loss: 0.0115 - val_mse: 0.0115
Epoch 60/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0077 - mse: 0.0077 - val_loss: 0.0115 - val_mse: 0.0115
Epoch 61/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0076 - mse: 0.0076 - val_loss: 0.0112 - val_mse: 0.0112
Epoch 62/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0074 - mse: 0.0074 - val_loss: 0.0111 - val_mse: 0.0111
Epoch 63/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0074 - mse: 0.0074 - val_loss: 0.0107 - val_mse: 0.0107
Epoch 64/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0073 - mse: 0.0073 - val_loss: 0.0107 - val_mse: 0.0107
Epoch 65/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0072 - mse: 0.0072 - val_loss: 0.0106 - val_mse: 0.0106
Epoch 66/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0070 - mse: 0.0070 - val_loss: 0.0106 - val_mse: 0.0106
Epoch 67/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0070 - mse: 0.0070 - val_loss: 0.0104 - val_mse: 0.0104
Epoch 68/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mse: 0.0069 - val_loss: 0.0102 - val_mse: 0.0102
Epoch 69/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0068 - mse: 0.0068 - val_loss: 0.0100 - val_mse: 0.0100
Epoch 70/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mse: 0.0068 - val_loss: 0.0097 - val_mse: 0.0097
Epoch 71/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0067 - mse: 0.0067 - val_loss: 0.0097 - val_mse: 0.0097
Epoch 72/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0066 - mse: 0.0066 - val_loss: 0.0096 - val_mse: 0.0096
Epoch 73/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0065 - mse: 0.0065 - val_loss: 0.0096 - val_mse: 0.0096
Epoch 74/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0065 - mse: 0.0065 - val_loss: 0.0095 - val_mse: 0.0095
Epoch 75/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0064 - mse: 0.0064 - val_loss: 0.0093 - val_mse: 0.0093
Epoch 76/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0063 - mse: 0.0063 - val_loss: 0.0092 - val_mse: 0.0092
Epoch 77/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0063 - mse: 0.0063 - val_loss: 0.0091 - val_mse: 0.0091
Epoch 78/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0062 - mse: 0.0062 - val_loss: 0.0089 - val_mse: 0.0089
Epoch 79/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0061 - mse: 0.0061 - val_loss: 0.0087 - val_mse: 0.0087
Epoch 80/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0061 - mse: 0.0061 - val_loss: 0.0088 - val_mse: 0.0088
Epoch 81/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mse: 0.0060 - val_loss: 0.0086 - val_mse: 0.0086
Epoch 82/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0062 - mse: 0.0062 - val_loss: 0.0086 - val_mse: 0.0086
Epoch 83/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mse: 0.0059 - val_loss: 0.0085 - val_mse: 0.0085
Epoch 84/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0058 - mse: 0.0058 - val_loss: 0.0083 - val_mse: 0.0083
Epoch 85/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0058 - mse: 0.0058 - val_loss: 0.0083 - val_mse: 0.0083
Epoch 86/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0058 - mse: 0.0058 - val_loss: 0.0083 - val_mse: 0.0083
Epoch 87/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mse: 0.0057 - val_loss: 0.0081 - val_mse: 0.0081
Epoch 88/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mse: 0.0056 - val_loss: 0.0080 - val_mse: 0.0080
Epoch 89/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mse: 0.0056 - val_loss: 0.0081 - val_mse: 0.0081
Epoch 90/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mse: 0.0055 - val_loss: 0.0079 - val_mse: 0.0079
Epoch 91/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mse: 0.0055 - val_loss: 0.0079 - val_mse: 0.0079
Epoch 92/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mse: 0.0055 - val_loss: 0.0078 - val_mse: 0.0078
Epoch 93/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mse: 0.0055 - val_loss: 0.0080 - val_mse: 0.0080
Epoch 94/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mse: 0.0054 - val_loss: 0.0077 - val_mse: 0.0077
Epoch 95/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0053 - mse: 0.0053 - val_loss: 0.0077 - val_mse: 0.0077
Epoch 96/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0053 - mse: 0.0053 - val_loss: 0.0076 - val_mse: 0.0076
Epoch 97/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0053 - mse: 0.0053 - val_loss: 0.0075 - val_mse: 0.0075
Epoch 98/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0052 - mse: 0.0052 - val_loss: 0.0074 - val_mse: 0.0074
Epoch 99/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0052 - mse: 0.0052 - val_loss: 0.0074 - val_mse: 0.0074
Epoch 100/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0052 - mse: 0.0052 - val_loss: 0.0074 - val_mse: 0.0074

In [16]:
y_lod=model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

In [17]:
y_lod

array([[0.6922715 ],
       [0.6935273 ],
       [0.9702985 ],
       [0.8420875 ],
       [0.6104787 ],
       [0.962529  ],
       [0.42315876],
       [0.46366394],
       [0.69864476],
       [0.829509  ],
       [0.67211956],
       [0.9393748 ],
       [0.4214884 ],
       [0.84936196],
       [0.69083965],
       [0.654955  ],
       [0.73608667],
       [0.38678902],
       [0.6599658 ],
       [0.94542134],
       [0.5529186 ],
       [0.61250025],
       [0.6827655 ],
       [0.571855  ],
       [0.9205995 ],
       [0.8654623 ],
       [0.70811605],
       [0.6100656 ],
       [0.63781196],
       [0.8199651 ],
       [0.82776946],
       [0.93370026],
       [0.6427311 ],
       [0.45465726],
       [0.6868748 ],
       [0.69147444],
       [0.7377083 ],
       [0.6242952 ],
       [0.597887  ],
       [0.9613961 ]], dtype=float32)

In [18]:
from sklearn.metrics import r2_score
mse=r2_score(y_test,y_lod)

In [19]:
mse

0.779281119259718