In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df= pd.read_csv("Housing_1.csv")

In [6]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [8]:
df["furnishingstatus"].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [9]:
le=LabelEncoder()

In [11]:
df["mainroad"]=le.fit_transform(df["mainroad"])
df["guestroom"]=le.fit_transform(df["guestroom"])
df["basement"]=le.fit_transform(df["basement"])
df["hotwaterheating"]=le.fit_transform(df["hotwaterheating"])
df["airconditioning"]=le.fit_transform(df["airconditioning"])
df["prefarea"]=le.fit_transform(df["prefarea"])
df["furnishingstatus"]=le.fit_transform(df["furnishingstatus"])

In [13]:
X=df.drop("price",axis=1)
y=df["price"]

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
scaler=StandardScaler()

In [16]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
import tensorflow
from keras.models import Sequential
from keras.layers import Dense

In [19]:
model=Sequential()

In [20]:
model.add(Dense(7,input_dim=12,activation="relu"))
model.add(Dense(5,activation="relu"))
model.add(Dense(1,activation="linear"))

In [32]:
model.compile(optimizer="adam",loss="mean_squared_error",metrics=["r2_score"])

In [33]:
model.fit(X_train,y_train,batch_size=80,epochs=50,verbose=1)

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 273ms/step - loss: 25234566545408.0000 - r2_score: -7.1840
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234558156800.0000 - r2_score: -7.1840
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234556059648.0000 - r2_score: -7.1840
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234551865344.0000 - r2_score: -7.1840
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234545573888.0000 - r2_score: -7.1840
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25234541379584.0000 - r2_score: -7.1840
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234535088128.0000 - r2_score: -7.1840
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234532990976.0000 - r2_score: -7.1840
Epoch 9/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234524602368.0000 - r2_score: -7.1840
Epoch 10/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234520408064.0000 - r2_score: -7.1840
Epoch 11/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234516213760.0000 - r2_score: -7.1840
Epoch 12/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234512019456.0000 - r2_score: -7.1840
Epoch 13/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234501533696.0000 - r2_score: -7.1840
Epoch 14/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234499436544.0000 - r2_score: -7.1840
Epoch 15/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234495242240.0000 - r2_score: -7.1840
Epoch 16/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234486853632.0000 - r2_score: -7.1840
Epoch 17/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234482659328.0000 - r2_score: -7.1840
Epoch 18/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234474270720.0000 - r2_score: -7.1840
Epoch 19/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234470076416.0000 - r2_score: -7.1840
Epoch 20/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234461687808.0000 - r2_score: -7.1840
Epoch 21/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234457493504.0000 - r2_score: -7.1840
Epoch 22/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234449104896.0000 - r2_score: -7.1840
Epoch 23/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25234442813440.0000 - r2_score: -7.1840
Epoch 24/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25234434424832.0000 - r2_score: -7.1840
Epoch 25/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234430230528.0000 - r2_score: -7.1840
Epoch 26/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234421841920.0000 - r2_score: -7.1840
Epoch 27/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234413453312.0000 - r2_score: -7.1840
Epoch 28/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234405064704.0000 - r2_score: -7.1840
Epoch 29/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234400870400.0000 - r2_score: -7.1840
Epoch 30/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234392481792.0000 - r2_score: -7.1840
Epoch 31/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234386190336.0000 - r2_score: -7.1840
Epoch 32/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234375704576.0000 - r2_score: -7.1840
Epoch 33/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234369413120.0000 - r2_score: -7.1840
Epoch 34/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234361024512.0000 - r2_score: -7.1840
Epoch 35/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234350538752.0000 - r2_score: -7.1840
Epoch 36/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234342150144.0000 - r2_score: -7.1840
Epoch 37/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234331664384.0000 - r2_score: -7.1839
Epoch 38/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234327470080.0000 - r2_score: -7.1840
Epoch 39/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25234316984320.0000 - r2_score: -7.1840
Epoch 40/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234306498560.0000 - r2_score: -7.1839
Epoch 41/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234300207104.0000 - r2_score: -7.1839
Epoch 42/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234287624192.0000 - r2_score: -7.1839
Epoch 43/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234277138432.0000 - r2_score: -7.1839
Epoch 44/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234266652672.0000 - r2_score: -7.1839
Epoch 45/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234258264064.0000 - r2_score: -7.1839
Epoch 46/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25234245681152.0000 - r2_score: -7.1839
Epoch 47/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234237292544.0000 - r2_score: -7.1839
Epoch 48/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234226806784.0000 - r2_score: -7.1839
Epoch 49/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234216321024.0000 - r2_score: -7.1839
Epoch 50/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25234205835264.0000 - r2_score: -7.1839

In [34]:
loss,r2_score=model.evaluate(X_test,y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - loss: 30129350770688.0000 - r2_score: -4.9608

In [35]:
loss

30129350770688.0

In [36]:
r2_score

-4.960813045501709